### ISSUE TITLE
vigenere.py 수정

### ISSUE THREAD

**Issue by bumsoo0515** [iwbh04/TextVault#17]
vigenere.py를 src/TextVault/ 폴더 안에 넣어주세요

그리고 Key class에 더 이상 self.encryptor는 없어서 해당 부분도 수정해주셔야 합니다.

_Originally posted by @bumsoo0515 in https://github.com/iwbh04/TextVault/issues/14#issuecomment-2524989897_

**Comment by Kmgskims** [comment]
잠시만요 확인해보겠습니다

**Comment by bumsoo0515** [comment]
https://github.com/iwbh04/TextVault/blob/master/src/TextVault/vigenere.py#L12

**Comment by bumsoo0515** [comment]
나머지는 한번 제가 고치고 PR 올릴 테니 확인해주세요

**Comment by Kmgskims** [comment]
넵
